<?php
	$col = array(
		'It is every man\'s obligation to put back into the world at least the equivalent of what he takes out of it. <br/><i>- Albert Einstein -</i>',
		'Life is like riding a bicycle - in order to keep your balance, you must keep moving. <br/><i>- Albert Einstein -</i>',
		'A man should look for what is, and not for what he thinks should be. <br/><i>- Albert Einstein -</i>',
		'A perfection of means, and confusion of aims, seems to be our main problem. <br/><i>- Albert Einstein -</i>',
		'A person who never made a mistake never tried anything new. <br/><i>- Albert Einstein -</i>',
		'A question that sometimes drives me hazy: am I or are the others crazy? <br/><i>- Albert Einstein -</i>',
		'A table, a chair, a bowl of fruit and a violin; what else does a man need to be happy? <br/><i>- Albert Einstein -</i>',
		'All religions, arts and sciences are branches of the same tree. <br/><i>- Albert Einstein -</i>',
		'All that is valuable in human society depends upon the opportunity for development accorded the individual. <br/><i>- Albert Einstein -</i>',
		'All these primary impulses, not easily described in words, are the springs of man\'s actions. <br/><i>- Albert Einstein -</i>',
		'An empty stomach is not a good political adviser. <br/><i>- Albert Einstein -</i>',
		'Anger dwells only in the bosom of fools. <br/><i>- Albert Einstein -</i>',
		'Any intelligent fool can make things bigger and more complex... It takes a touch of genius - and a lot of courage to move in the opposite direction. <br/><i>- Albert Einstein -</i>',
		'Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves. <br/><i>- Albert Einstein -</i>',
		'Any man who reads too much and uses his own brain too little falls into lazy habits of thinking. <br/><i>- Albert Einstein -</i>',
		'Anyone who doesn\'t take truth seriously in small matters cannot be trusted in large ones either. <br/><i>- Albert Einstein -</i>',
		'Anyone who has never made a mistake has never tried anything new. <br/><i>- Albert Einstein -</i>',
		'As far as I\'m concerned, I prefer silent vice to ostentatious virtue. <br/><i>- Albert Einstein -</i>',
		'As far as the laws of mathematics refer to reality, they are not certain, and as far as they are certain, they do not refer to reality. <br/><i>- Albert Einstein -</i>',
		'Before God we are all equally wise - and equally foolish. <br/><i>- Albert Einstein -</i>',
		'Common sense is the collection of prejudices acquired by age eighteen. <br/><i>- Albert Einstein -</i>',
		'Concern for man and his fate must always form the chief interest of all technical endeavors. Never forget this in the midst of your diagrams and equations. <br/><i>- Albert Einstein -</i>',
		'We all try to escape pain and death, while we seek what is pleasant. <br/><i>- Albert Einstein -</i>',
		'LOVE: He to whom this emotion is a stranger, who can no longer pause to wonder and stand rapt in awe, is as good as dead: his eyes are closed. <br/><i>- Albert Einstein -</i>',
		'The difference between what the most and the least learned people know is inexpressibly trivial in relation to that which is unknown. <br/><i>- Albert Einstein -</i>',
		'No, this trick won\'t work...How on earth are you ever going to explain in terms of chemistry and physics so important a biological phenomenon as first love?. <br/><i>- Albert Einstein -</i>',
		'The finest emotion of which we are capable is the mystic emotion. Herein lies the germ of all art and all true science. Anyone to whom this feeling is alien, who is no longer capable of wonderment and lives in a state of fear is a dead man. To know that what is impenatrable for us really exists and manifests itself as the highest wisdom and the most radiant beauty, whose gross forms alone are intelligible to our poor faculties - this knowledge, this feeling ... that is the core of the true religious sentiment. In this sense, and in this sense alone, I rank myself amoung profoundly religious men. <br/><i>- Albert Einstein -</i>',
		'An attempt at visualizing the Fourth Dimension: Take a point, stretch it into a line, curl it into a circle, twist it into a sphere, and punch through the sphere. <br/><i>- Albert Einstein -</i>',
		'My life is a simple thing that would interest no one. It is a known fact that I was born and that is all that is necessary. <br/><i>- Albert Einstein -</i>',
		'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. <br/><i>- Albert Einstein -</i>',
		'Only a life lived in the service to others is worth living. <br/><i>- Albert Einstein -</i>',
		'The attempt to combine wisdom and power has only rarely been successful and then only for a short while. <br/><i>- Albert Einstein -</i>',
		'Unless Americans come to realize that they are not stronger in the world because they have the bomb but weaker because of their vulnerability to atomic attack, they are not likely to conduct their policy at Lake Success [the United Nations] or in their relations with Russia in a spirit that furthers the arrival at an understanding. <br/><i>- Albert Einstein -</i>',
		'What I see in Nature is a magnificent structure that we can comprehend only very imperfectly, and that must fill a thinking person with a feeling of humility. This is a genuinely religious feeling that has nothing to do with mysticism. <br/><i>- Albert Einstein -</i>',
		'It is a magnificent feeling to recognize the unity of complex phenomena which appear to be things quite apart from the direct visible truth. <br/><i>- Albert Einstein -</i>',
		'Men marry women with the hope they will never change. Women marry men with the hope they will change. Invariably they are both disappointed. <br/><i>- Albert Einstein -</i>',
		'The bitter and the sweet come from the outside, the hard from within, from one\'s own efforts. <br/><i>- Albert Einstein -</i>',
	);
?>