<?php
	$col = array(
		'Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness, that most frightens us. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won\'t feel insecure around you. We are all meant to shine as children do. It\'s not just in some of us; it is in everyone. And as we let our own lights shine, we unconsciously give other people permission to do the same. As we are liberated from our own fear, our presence automatically liberates others. <br/><i>- Nelson Mandela -</i>',
		'Education is the great engine of personal development. It is through education that the daughter of a peasant can become a doctor, that a son of a mineworker can become the head of the mine, that a child of farm workers can become the president... <br/><i>- Nelson Mandela -</i>',
		'How can I be expected to believe that this same racial discrimination which has been the cause of so much injustice and suffering right through the years, should now operate here to give me a fair and open trial?....consider myself neither morally nor legally obliged to obey laws made by a Parliament in which I am not represented. That the will of the people is the basis of the authority of government, is a principle universally acknowledged as sacred throughout the civilized world. <br/><i>- Nelson Mandela -</i>',
		'And as we let our own light shine, we unconsciously give other people permission to do the same. <br/><i>- Nelson Mandela -</i>',
		'As we are liberated from our own fear, our presence automatically liberates others. <br/><i>- Nelson Mandela -</i>',
		'We need to exert ourselves that much more, and break out of the vicious cycle of dependence imposed on us by the financially powerful: those in command of immense market power and those who dare to fashion the world in their own image. <br/><i>- Nelson Mandela -</i>',
		'The curious beauty of African music is that it uplifts even as it tells a sad tale. You may be poor, you may have only a ramshackle house, you may have lost your job, but that song gives you hope. African music is often about the aspirations of the African. <br/><i>- Nelson Mandela -</i>',
		'I have walked that long road to freedom. I have tried not to falter; I have made missteps along the way. But I have discovered the secret that after climbing a great hill, one only finds that there are many more hills to climb. I have taken a moment. <br/><i>- Nelson Mandela -</i>',
		'If you talk to a man in a language he understands, that goes to his head. If you talk to him in his language, that goes to his heart. <br/><i>- Nelson Mandela -</i>',
		'When I think about the past, the types of things they did, I feel angry, but then again that is my feeling. The brain always dominates, says, as I have pointed out, you have a limited time to stay on Earth. <br/><i>- Nelson Mandela -</i>',
		'A good head and a good heart are always a formidable combination. <br/><i>- Nelson Mandela -</i>',
		'After climbing a great hill, one only finds that there are many more hills to climb. <br/><i>- Nelson Mandela -</i>',
		'There can be no keener revelation of a society\'s soul than the way in which it treats its children. <br/><i>- Nelson Mandela -</i>',
		'When the water starts boiling it is foolish to turn off the heat. <br/><i>- Nelson Mandela -</i>',
		'I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear. <br/><i>- Nelson Mandela -</i>',
	);
?>