<?php
	$db = array(
		'It is every man\'s obligation to put back into the world at least the equivalent of what he takes out of it. <br/><i>- Albert Einstein -</i>',
		'Life is like riding a bicycle - in order to keep your balance, you must keep moving. <br/><i>- Albert Einstein -</i>',
		'A man should look for what is, and not for what he thinks should be. <br/><i>- Albert Einstein -</i>',
		'A perfection of means, and confusion of aims, seems to be our main problem. <br/><i>- Albert Einstein -</i>',
		'A person who never made a mistake never tried anything new. <br/><i>- Albert Einstein -</i>',
		'A question that sometimes drives me hazy: am I or are the others crazy? <br/><i>- Albert Einstein -</i>',
		'A table, a chair, a bowl of fruit and a violin; what else does a man need to be happy? <br/><i>- Albert Einstein -</i>',
		'All religions, arts and sciences are branches of the same tree. <br/><i>- Albert Einstein -</i>',
		'All that is valuable in human society depends upon the opportunity for development accorded the individual. <br/><i>- Albert Einstein -</i>',
		'All these primary impulses, not easily described in words, are the springs of man\'s actions. <br/><i>- Albert Einstein -</i>',
		'An empty stomach is not a good political adviser. <br/><i>- Albert Einstein -</i>',
		'Anger dwells only in the bosom of fools. <br/><i>- Albert Einstein -</i>',
		'Any intelligent fool can make things bigger and more complex... It takes a touch of genius - and a lot of courage to move in the opposite direction. <br/><i>- Albert Einstein -</i>',
		'Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves. <br/><i>- Albert Einstein -</i>',
		'Any man who reads too much and uses his own brain too little falls into lazy habits of thinking. <br/><i>- Albert Einstein -</i>',
		'Anyone who doesn\'t take truth seriously in small matters cannot be trusted in large ones either. <br/><i>- Albert Einstein -</i>',
		'Anyone who has never made a mistake has never tried anything new. <br/><i>- Albert Einstein -</i>',
		'As far as I\'m concerned, I prefer silent vice to ostentatious virtue. <br/><i>- Albert Einstein -</i>',
		'As far as the laws of mathematics refer to reality, they are not certain, and as far as they are certain, they do not refer to reality. <br/><i>- Albert Einstein -</i>',
		'Before God we are all equally wise - and equally foolish. <br/><i>- Albert Einstein -</i>',
		'Common sense is the collection of prejudices acquired by age eighteen. <br/><i>- Albert Einstein -</i>',
		'Concern for man and his fate must always form the chief interest of all technical endeavors. Never forget this in the midst of your diagrams and equations. <br/><i>- Albert Einstein -</i>',
	);
?>