<?php
	$db = array(
		'Faithfulness and sincerity are the highest things. <br/><i>- Confucius -</i>',
		'It is not possible for one to teach others who cannot teach his own family. <br/><i>- Confucius -</i>',
		'Man who stand on hill with mouth open will wait long time for roast duck to drop in. <br/><i>- Confucius -</i>',
		'The parents age must be remembered, both for joy and anxiety. <br/><i>- Confucius -</i>',
		'Do not be desirous of having things done quickly. Do not look at small advantages. Desire to have things done quickly prevents their being done thoroughly. Looking at small advantages prevents great affairs from being accomplished. <br/><i>- Confucius -</i>',
		'The father who does not teach his son his duties is equally guilty with the son who neglects them. <br/><i>- Confucius -</i>',
		'The perfecting of one\'s self is the fundamental base of all progress and all moral development. <br/><i>- Confucius -</i>',
		'If you lead the people with correctness, who will dare not be correct? <br/><i>- Confucius -</i>',
		'A fool despises good counsel, but a wise man takes it to heart. <br/><i>- Confucius -</i>',
		'Recompense injury with justice, and recompense kindness with kindness. <br/><i>- Confucius -</i>',
		'With coarse rice to eat, with water to drink, and my bent arm for a pillow -- I have still joy in the midst of all these things. <br/><i>- Confucius -</i>',
		'Mankind differs from the animals only by a little and most people throw that away. <br/><i>- Confucius -</i>',
		'A man who has committed a mistake and doesn\'t correct it is committing another mistake. <br/><i>- Confucius -</i>',
		'Our greatest glory is not in never falling, but in rising every time we fall. <br/><i>- Confucius -</i>',
		'We take greater pains to persuade others we are happy than in trying to think so ourselves. <br/><i>- Confucius -</i>',
		'By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest. <br/><i>- Confucius -</i>',
		'To be fond of learning is near to wisdom; to practice with vigor is near to benevolence; and to be conscious of shame is near to fortitude. He who knows these three things. <br/><i>- Confucius -</i>',
		'If you look into your own heart, you find nothing wrong there, what is there to fear? <br/><i>- Confucius -</i>',
		'The wheel of fortune turns round incessantly, and who can say to himself, &quot;I shall today be uppermost.&quot; <br/><i>- Confucius -</i>',
		'When we see men of a contrary character, we should turn inwards and examine ourselves. <br/><i>- Confucius -</i>',
		'When you see a worthy person, endeavor to emulate him. When you see an unworthy person, then examine your inner self. <br/><i>- Confucius -</i>',
		'To put the world right in order, we must first put the nation in order; to put the nation in order, we must first put the family in order; to put the family in order, we must first cultivate our personal life; we must first set our hearts right. <br/><i>- Confucius -</i>',
		'I am not concerned that I am not known, I seek to be worthy to be known. <br/><i>- Confucius -</i>',
		'The essence of knowledge is, having it, to apply it; not having it, to confess your ignorance. <br/><i>- Confucius -</i>',
		'He who conquers himself is the mightiest warrior. <br/><i>- Confucius -</i>',
		'It is only the wisest and the stupidest that cannot change. <br/><i>- Confucius -</i>',
		'Worry not that no one knows of you; seek to be worth knowing. <br/><i>- Confucius -</i>',
		'The way of the superior person is threefold; virtuous, they are free from anxieties; wise they are free from perplexities; and bold they are free from fear. <br/><i>- Confucius -</i>',
		'Study the past, if you would divine the future. <br/><i>- Confucius -</i>',
		'Don\'t complain about the snow on your neighbor\'s roof when your own doorstep is unclean. <br/><i>- Confucius -</i>',
		'The faults of a superior person are like the sun and moon. They have their faults, and everyone sees them; they change and everyone looks up to them. <br/><i>- Confucius -</i>',
	);
?>