<?php
	$db = array(
		'I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin, but by the content of their character. <br/><i>- Martin Luther King, Jr. -</i>',
		'The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy. <br/><i>- Martin Luther King, Jr. -</i>',
		'Our lives begin to end the day we become silent about things that matter. <br/><i>- Martin Luther King, Jr. -</i>',
		'Our loyalties must transend our race, our tribe, our class, and our nation; and this means we must develop a world perspective. <br/><i>- Martin Luther King, Jr. -</i>',
		'Hatred paralyzes life; love releases it. Hatred confuses life; love harmonizes it. Hatred darkens life; love illuminates it. <br/><i>- Martin Luther King, Jr. -</i>',
		'If you come with no agenda, you will become the agenda. <br/><i>- Martin Luther King, Jr. -</i>',
		'Occasionally in life there are those moments of unutterable fulfillment which cannot be completely explained by those symbols called words. Their meanings can only be articulated by the inaudible language of the heart. <br/><i>- Martin Luther King, Jr. -</i>',
		'Everybody can be great... because anybody can serve. You don\'t have to have a college degree to serve. You don\'t have to make your subject and verb agree to serve. you only need a heart full of grace. a soul generated by love. <br/><i>- Martin Luther King, Jr. -</i>',
		'In the End, we will remember not the words of our enemies, but the silence of our friends. <br/><i>- Martin Luther King, Jr. -</i>',
		'I have almost reached the regrettable conclusion that the Negro\'s great stumbling block in his stride toward freedom is not the White Citizen\'s Councilor or the Ku Klux Klanner, but the white moderate. <br/><i>- Martin Luther King, Jr. -</i>',
		'I have a dream that one day this nation will rise up and live out the true meaning of its creed; We hold these truths to be self-evident: that all men are created equal. <br/><i>- Martin Luther King, Jr. -</i>',
		'Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that. <br/><i>- Martin Luther King, Jr. -</i>',
		'He who passively accepts evil is as much involved in it as he who helps to perpetrate it. <br/><i>- Martin Luther King, Jr. -</i>',
		'It is my hope that as the Negro plunges deeper into the quest for freedom and justice he will plunge even deeper into the philosophy of non-violence. The Negro all over the South must come to the point that he can say to his white brother: &quot;We will match your capacity to inflict suffering with our capacity to endure suffering. We will meet your physical force with soul force. We will not hate you, but we will not obey your evil laws. We will soon wear you down by pure capacity to suffer.&quot; <br/><i>- Martin Luther King, Jr. -</i>',
	);
?>