<?php
	$db = array(
		'Be faithful in small things because it is in them that your strength lies. <br/><i>- Mother Teresa -</i>',
		'Being unwanted, unloved, uncared for, forgotten by everybody, I think that is a much greater hunger, a much greater poverty than the person who has nothing to eat. <br/><i>- Mother Teresa -</i>',
		'Do not think that love, in order to be genuine, has to be extraordinary. What we need is to love without getting tired. <br/><i>- Mother Teresa -</i>',
		'Do not wait for leaders; do it alone, person to person. <br/><i>- Mother Teresa -</i>',
		'Each one of them is Jesus in disguise. <br/><i>- Mother Teresa -</i>',
		'Even the rich are hungry for love, for being cared for, for being wanted, for having someone to call their own. <br/><i>- Mother Teresa -</i>',
		'Everytime you smile at someone, it is an action of love, a gift to that person, a beautiful thing. <br/><i>- Mother Teresa -</i>',
		'God doesn\'t require us to succeed; he only requires that you try. <br/><i>- Mother Teresa -</i>',
		'Good works are links that form a chain of love. <br/><i>- Mother Teresa -</i>',
		'I am a little pencil in the hand of a writing God who is sending a love letter to the world. <br/><i>- Mother Teresa -</i>',
		'Never miss an opportunity to make others happy, even if you have to leave them alone in order to do it. <br/><i>- Mother Teresa -</i>',
		'I do not pray for success, I ask for faithfulness. <br/><i>- Mother Teresa -</i>',
		'I have found the paradox, that if you love until it hurts, there can be no more hurt, only more love. <br/><i>- Mother Teresa -</i>',
		'I know God will not give me anything I can\'t handle. I just wish that He didn\'t trust me so much. <br/><i>- Mother Teresa -</i>',
		'I try to give to the poor people for love what the rich could get for money. No, I wouldn\'t touch a leper for a thousand pounds; yet I willingly cure him for the love of God. <br/><i>- Mother Teresa -</i>',
		'I want you to be concerned about your next door neighbor. Do you know your next door neighbor? <br/><i>- Mother Teresa -</i>',
		'If we have no peace, it is because we have forgotten that we belong to each other. <br/><i>- Mother Teresa -</i>',
		'If we want a love message to be heard, it has got to be sent out. To keep a lamp burning, we have to keep putting oil in it. <br/><i>- Mother Teresa -</i>',
		'If you can\'t feed a hundred people, then feed just one. <br/><i>- Mother Teresa -</i>',
		'If you judge people, you have no time to love them. <br/><i>- Mother Teresa -</i>',
		'If you want a love message to be heard, it has got to be sent out. To keep a lamp burning, we have to keep putting oil in it. <br/><i>- Mother Teresa -</i>',
	);
?>