<?php
	$db = array(
		'Be kind, for everyone you meet is fighting a hard battle. <br/><i>- Plato -</i>',
		'Death is not the worst that can happen to men. <br/><i>- Plato -</i>',
		'If women are expected to do the same work as men, we must teach them the same things. <br/><i>- Plato -</i>',
		'Ignorance, the root and the stem of every evil. <br/><i>- Plato -</i>',
		'Laws are partly formed for the sake of good men, in order to instruct them how they may live on friendly terms with one another, and partly for the sake of those who refuse to be instructed, whose spirit cannot be subdued, or softened, or hindered from plunging into evil. <br/><i>- Plato -</i>',
		'Man...is a tame or civilized animal; never the less, he requires proper instruction and a fortunate nature, and then of all animals he becomes the most divine and most civilized; but if he be insufficiently or ill- educated he is the most savage of earthly creatures. <br/><i>- Plato -</i>',
		'Never discourage anyone... who continually makes progress, no matter how slow. <br/><i>- Plato -</i>',
		'No human thing is of serious importance. <br/><i>- Plato -</i>',
		'Only the dead have seen the end of war. <br/><i>- Plato -</i>',
		'The price good men pay for indifference to public affairs is to be ruled by evil men. <br/><i>- Plato -</i>',
		'There is no such thing as a lover\'s oath. <br/><i>- Plato -</i>',
		'They certainly give very strange names to diseases. <br/><i>- Plato -</i>',
		'We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. <br/><i>- Plato -</i>',
		'Wise men talk because they have something to say; fools, because they have to say something. <br/><i>- Plato -</i>',
		'You can discover more about a person in an hour of play than in a year of conversation. <br/><i>- Plato -</i>',
		'No evil can happen to a good man, either in life or after death. <br/><i>- Plato -</i>',
		'You cannot conceive the many without the one. <br/><i>- Plato -</i>',
		'False words are not only evil in themselves, but they infect the soul with evil. <br/><i>- Plato -</i>',
		'Must not all things at the last be swallowed up in death? <br/><i>- Plato -</i>',
		'The partisan, when he is engaged in a dispute, cares nothing about the rights of the question, but is anxious only to convince his hearers of his own assertions. <br/><i>- Plato -</i>',
		'Friends have all things in common. <br/><i>- Plato -</i>',
		'The greatest penalty of evildoing - namely, to grow into the likeness of bad men. <br/><i>- Plato -</i>',
		'You are young, my son, and, as the years go by, time will change and even reverse many of your present opinions. Refrain therefore awhile from setting yourself up as a judge of the highest matters. <br/><i>- Plato -</i>',
		'Any one who has common sense will remember that the bewilderments of the eyes are of two kinds, and arise from two causes, either from coming out of the light or from going into the light, which is true of the mind\'s eye, quite as much as of the bodily eye; and he who remembers this when he sees any one whose vision is perplexed and weak, will not be too ready to laugh; he will first ask whether that soul of man has come out of the brighter light, and is unable to see because unaccustomed to the dark, or having turned from darkness to the day is dazzled by excess of light. <br/><i>- Plato -</i>',
		'Astronomy compels the soul to look upwards and leads us from this world to another. <br/><i>- Plato -</i>',
		'Bodily exercise, when compulsory, does no harm to the body; but knowledge which is acquired under compulsion obtains no hold on the mind. <br/><i>- Plato -</i>',
		'Everything that deceives may be said to enchant. <br/><i>- Plato -</i>',
		'He who is of calm and happy nature will hardly feel the pressure of age, but to him who is of an opposite disposition youth and age are equally a burden. <br/><i>- Plato -</i>',
	);
?>