<?php
	$db = array(
		'You\'ve got a lot of choices.  If getting out of bed in the morning is a chore and you\'re not smiling on a regular basis, try another choice. <br/><i>- Steven D. Woodhull -</i>',
		'What saves a man is to take a step.  Then another step.  It is always the same step, but you have to take it. <br/><i>- Antoine de Saint-Exupéry -</i>',
		'Don\'t wait for the Last Judgment. It happens every day. <br/><i>- Albert Camus -</i>',
		'Good for the body is the work of the body, and good for the soul is the work of the soul, and good for either is the work of the other. <br/><i>- Henry David Thoreau -</i>',
		'Anyone can carry his burden, however hard, until nightfall.  Anyone can do his work, however hard, for one day.  Anyone can live sweetly, patiently, lovingly, purely, till the sun goes down.  And this is all life really means. <br/><i>- Robert Louis Stevenson -</i>',
		'If you don\'t like how things are, change it!  You\'re not a tree. <br/><i>- Jim Rohn -</i>',
		'See everything; overlook a great deal; correct a little. <br/><i>- Pope John XXIII -</i>',
		'Give thanks for what you are now, and keep fighting for what you want to be tomorrow. <br/><i>- Fernanda Miramontes-Landeros -</i>',
		'Enjoy when you can, and endure when you must. <br/><i>- Johann Wolfgang von Goethe -</i>',
		'Now that it\'s all over, what did you really do yesterday that\'s worth mentioning? <br/><i>- Coleman Cox -</i>',
		'If you surrender to the wind, you can ride it. <br/><i>- Toni Morrison -</i>',
		'Never miss an opportunity to make others happy, even if you have to leave them alone in order to do it.',
		'Sometimes it\'s more important to be human, than to have good taste. <br/><i>- Brecht -</i>',
		'We have to live today by what truth we can get today and be ready tomorrow to call it falsehood. <br/><i>- William James -</i>',
		'You can tell more about a person by what he says about others than you can by what others say about him. <br/><i>- Leo Aikman -</i>',
		'Seek freedom and become captive of your desires.  Seek discipline and find your liberty. <br/><i>- Frank Herbert, Dune Chronicles -</i>',
		'The first and greatest victory is to conquer yourself; to be conquered by yourself is of all things most shameful and vile. <br/><i>- Plato -</i>',
		'Pick battles big enough to matter, small enough to win. <br/><i>- Jonathan Kozel -</i>',
		'Tough and funny and a little bit kind:  that is as near to perfection as a human being can be. <br/><i>- Mignon McLaughlin, -</i>',
		'Do what you can, with what you have, where you are. <br/><i>- Theodore Roosevelt -</i>',
		'Face what you think you believe and you will be surprised. <br/><i>- William Hale White -</i>',
		'Don\'t look where you fall, but where you slipped. <br/><i>- African Proverb -</i>',
		'The important thing is this:  To be able at any moment to sacrifice that which we are for what we could become. <br/><i>- Charles DuBois -</i>',
		'Time you enjoy wasting, was not wasted. <br/><i>- John Lennon -</i>',
		'Don\'t judge each day by the harvest you reap but by the seeds that you plant. <br/><i>- Robert Louis Stevenson -</i>',
		'In this age, which believes that there is a short cut to everything, the greatest lesson to be learned is that the most difficult way is, in the long run, the easiest. <br/><i>- Henry Miller, -</i>',
		'Whatever you are be a good one. <br/><i>- Abraham Lincoln -</i>',
		'Think of your faults the first part of the night when you are awake, and the faults of others the latter part of the night when you are asleep. <br/><i>- Chinese Proverb -</i>',
		'When "Why not do it?" barely outweights "Why do it?" - don\'t do it. <br/><i>- Mignon McLaughlin -</i>',
		'The biggest problem in the world<br/>Could have been solved when it was small. <br/><i>- Witter Bynner -</i>',
		'A man begins cutting his wisdom teeth the first time he bites off more than he can chew. <br/><i>- Herb Caen -</i>',
		'A prudent question is one-half of wisdom. <br/><i>- Francis Bacon -</i>',
		'Cleverness is not wisdom. <br/><i>- Euripides -</i>',
		'Every man is a damn fool for at least five minutes every day; wisdom consists in not exceeding the limit. <br/><i>- Elbert Hubbard -</i>',
		'He dares to be a fool, and that is the first step in the direction of wisdom. <br/><i>- James Huneker -</i>',
		'He who devotes sixteen hours a day to hard study may become at sixty as wise as he thought himself at twenty. <br/><i>- Mary Wilson Little -</i>',
		'Honesty is the first chapter in the book of wisdom. <br/><i>- Thomas Jefferson -</i>'
	);
?>